%YAML 1.2
---
spec:
  validation:
    ignore_uris_containing:
      - /resources/vocabularies/conceptschemes/
      - /resources/vocabularies/ActorFamilie/
      - /resources/vocabularies/ActorPersoon/
      - /resources/vocabularies/ArchiefBlok/
      # Negeer record URIs
      - https://lei-migrate.memorix.io/resources/records/
      # Negeer SKOS concept URIs
      - https://lei-migrate.memorix.io/resources/vocabularies/concepts/
    # De "done" items worden gecontroleerd met het validatiescript
    done:
      - Archiefblok
    # De "todo" items worden overgeslagen door het validatiescript
    todo:
      - Aanwinst
      - ActorFamilie
      - ActorOrganisatie
      - ActorPersoon
      - Archiefbibliotheek
      - Av
      - Bestanddeel
      - Bibliotheek
      - Bijlage
      - BlaeuAtlas
      - BlaeuAtlasPagina
      - Complex
      - DanielvdMeulen
      - Deed
      - ErfgoedregisterAdres
      - Groep
      - HeiligeGeestWeeshuis
      - Image
      - Koorboek
      - KoorboekPagina
      - LeFranqVanBerkhey
      - Object
      - Organisatie
      - Persoon
      - Persoonsvermelding
      - Restauratie
      - Woii
